apiVersion: kopf.dev/v1
kind: NatsExample
metadata:
  name: "{name}"
  labels:
    somelabel: somevalue
  annotations:
    someannotation: somevalue
spec:
  duration: 1m
  field: value
  items:
  - item1
  - item2
